[[tool.mypy.overrides]]
module = "*"
ignore_missing_imports = true

[tool.poetry]
name = "fistashkinbot"
version = "1.7"
description = ""
authors = ["riverya4life"]
readme = "README.md"
repository = "https://github.com/fistashkinbot/FistashkinBot-Beta"
